name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy 1 to GitHub Pages
        uses: actions/deploy@v1
        with:
          github_token: ${{ secrets.ACTIONS_SECRET }}
          folder: dist
